### ISSUE TITLE
ECS

### ISSUE THREAD

**Issue by DrSensor** [DrSensor/nusa#13]
This ECS feature are more like my toy experiment rather than serious one. Although no one ask for this 😂, code composition for multiple logics that constantly in a loop while updating the retained GUI (DOM) are damn so hard.

> **Note** ECS usages are not limited to gamedev or logic that constantly in a loop. ECS is a composition pattern that specifically optimized for doing mass control.

- [x] Struct of Array (any type)
- [ ] Struct of TypedArray
- [ ] Struct of Boolean as BitSet (use case: Tag component)
- [ ] SparseSet and BitSet entities
  - [ ] `@allocate` decorator
  - [ ] function to `kill(entity)` (reset component value)
  - [ ] function to `suspend(entity)` and `resume(entity)` (doesn't reset component value)
- [ ] Archetype graph
  - [ ] function to `.add(components)` from an entity
  - [ ] function to `.remove(components)` from an entity
  - [ ] `query(components)`
- [ ] async `system = () => ...`
  - [ ] global `dt` (delta time)
  - [ ] local `system.dt`
  - [ ] pseudo async primitive that doesn't queue into microtask
  - [ ] explicit [OMT](https://web.dev/off-main-thread/) system across spectrum: worker, wasm, compute shader. (require more exploration)
- [ ] #15

**Comment by DrSensor** [comment]
Moved to #55 #56
